package com.example.yasirnazir.curve

import android.app.Application
import com.example.yasirnazir.curve.di.AppComponent
import com.facebook.stetho.Stetho


class MyApp : Application() {
    var applicationComponent: AppComponent? = null
        private set

    override fun onCreate() {
        super.onCreate()
        val initializerBuilder = Stetho.newInitializerBuilder(this)

        initializerBuilder.enableWebKitInspector(
                Stetho.defaultInspectorModulesProvider(this)
        )

        val initializer = initializerBuilder.build()

        Stetho.initialize(initializer)
        // DaggerAppComponent is not generated by dagger.
        //  applicationComponent = DaggerAppComponent.builder().application(this).build()
        applicationComponent?.inject(this)
    }
}